//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUni.Web.UI.SiteMap {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootDepartmentsControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootDepartmentsControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Index() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "", "Departments", "Index", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "Index", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Show(string departmentName) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "", "Departments", "Show", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "Show", new System.Type[] {
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "departmentName", typeof(string), departmentName)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference Show() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "", "Departments", "Show", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "Show", new System.Type[] {
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHomeControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootHomeControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Index() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.HomeController), "", "Home", "Index", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.HomeController), "Index", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference About() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.HomeController), "", "Home", "About", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.HomeController), "About", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLoginControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootLoginControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Login(string returnUrl) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.LoginController), "", "Login", "Login", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.LoginController), "Login", new System.Type[] {
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "returnUrl", typeof(string), returnUrl)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Login(string returnUrl, int icn, string username, string password) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.LoginController), "", "Login", "Login", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.LoginController), "Login", new System.Type[] {
                            typeof(string),
                            typeof(int),
                            typeof(string),
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "returnUrl", typeof(string), returnUrl),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(1, "icn", typeof(int), icn),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(2, "username", typeof(string), username),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(3, "password", typeof(string), password)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Logout() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.LoginController), "", "Login", "Logout", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.LoginController), "Logout", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference ChooseRole(OpenUni.Domain.People.Roles role) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.LoginController), "", "Login", "ChooseRole", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.LoginController), "ChooseRole", new System.Type[] {
                            typeof(OpenUni.Domain.People.Roles)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "role", typeof(OpenUni.Domain.People.Roles), role)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference ChooseRole() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.LoginController), "", "Login", "ChooseRole", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.LoginController), "ChooseRole", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootModulesControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootModulesControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Index(OpenUni.Domain.Modules.ModuleSpecification specification) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.ModulesController), "", "Modules", "Index", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.ModulesController), "Index", new System.Type[] {
                            typeof(OpenUni.Domain.Modules.ModuleSpecification)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "specification", typeof(OpenUni.Domain.Modules.ModuleSpecification), specification)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference Index() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.ModulesController), "", "Modules", "Index", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.ModulesController), "Index", new System.Type[] {
                            typeof(OpenUni.Domain.Modules.ModuleSpecification)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Show(int moduleId, string moduleName) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.ModulesController), "", "Modules", "Show", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.ModulesController), "Show", new System.Type[] {
                            typeof(int),
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "moduleId", typeof(int), moduleId),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(1, "moduleName", typeof(string), moduleName)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference Show() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.ModulesController), "", "Modules", "Show", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.ModulesController), "Show", new System.Type[] {
                            typeof(int),
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootSqlLogControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootSqlLogControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference View(int requestId) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.SqlLogController), "", "SqlLog", "View", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.SqlLogController), "View", new System.Type[] {
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "requestId", typeof(int), requestId)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference View() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.SqlLogController), "", "SqlLog", "View", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.SqlLogController), "View", new System.Type[] {
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Cache() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.SqlLogController), "", "SqlLog", "Cache", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.SqlLogController), "Cache", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalHomeControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPortalHomeControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Index() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.HomeController), "Portal", "Home", "Index", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.Portal.HomeController), "Index", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalModulesControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPortalModulesControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference MyModules() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Portal", "Modules", "MyModules", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "MyModules", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Register(int moduleId, int year, byte term) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Portal", "Modules", "Register", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Register", new System.Type[] {
                            typeof(int),
                            typeof(int),
                            typeof(byte)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "moduleId", typeof(int), moduleId),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(1, "year", typeof(int), year),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(2, "term", typeof(byte), term)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Registered() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Portal", "Modules", "Registered", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Registered", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Register() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Portal", "Modules", "Register", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Register", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPeopleProfilesControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPeopleProfilesControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Show(string username, System.Guid personId) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.People.ProfilesController), "People", "Profiles", "Show", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.People.ProfilesController), "Show", new System.Type[] {
                            typeof(string),
                            typeof(System.Guid)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "username", typeof(string), username),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(1, "personId", typeof(System.Guid), personId)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference Show() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(OpenUni.Web.UI.Controllers.People.ProfilesController), "People", "Profiles", "Show", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(OpenUni.Web.UI.Controllers.People.ProfilesController), "Show", new System.Type[] {
                            typeof(string),
                            typeof(System.Guid)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootDepartmentsControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootDepartmentsControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RouteDefinitions {
        
        /// <summary>
        /// departments
        /// </summary>
        public static DepartmentsRoute Departments {
            get {
                return ((DepartmentsRoute)(new DepartmentsRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.DepartmentsController>().DefaultForAction().Is("Index")));
            }
        }
        
        /// <summary>
        /// departments/&lt;departmentName&gt;
        /// </summary>
        public static DepartmentByNameRoute DepartmentByName {
            get {
                return ((DepartmentByNameRoute)(new DepartmentByNameRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.DepartmentsController>().DefaultForAction().Is("Show")));
            }
        }
        
        /// <summary>
        /// /[controller]
        /// </summary>
        public static HomepageRoute Homepage {
            get {
                return ((HomepageRoute)(new HomepageRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.HomeController>().DefaultForAction().Is("Index")));
            }
        }
        
        /// <summary>
        /// /about
        /// </summary>
        public static aboutRoute about {
            get {
                return ((aboutRoute)(new aboutRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.HomeController>().DefaultForAction().Is("About")));
            }
        }
        
        /// <summary>
        /// login
        /// </summary>
        public static LoginRoute Login {
            get {
                return ((LoginRoute)(new LoginRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.LoginController>().DefaultForAction().Is("Login")));
            }
        }
        
        /// <summary>
        /// login/logout
        /// </summary>
        public static LogoutRoute Logout {
            get {
                return ((LogoutRoute)(new LogoutRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.LoginController>().DefaultForAction().Is("Logout")));
            }
        }
        
        /// <summary>
        /// login/chooserole
        /// </summary>
        public static Login_ChooseRoleRoute Login_ChooseRole {
            get {
                return ((Login_ChooseRoleRoute)(new Login_ChooseRoleRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.LoginController>().DefaultForAction().Is("ChooseRole")));
            }
        }
        
        /// <summary>
        /// modules
        /// </summary>
        public static ModulesRoute Modules {
            get {
                return ((ModulesRoute)(new ModulesRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.ModulesController>().DefaultForAction().Is("Index")));
            }
        }
        
        /// <summary>
        /// modules/&lt;moduleId:int&gt;/[moduleName]
        /// </summary>
        public static ModuleByIdRoute ModuleById {
            get {
                return ((ModuleByIdRoute)(new ModuleByIdRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.ModulesController>().DefaultForAction().Is("Show").Restrict(ModuleByIdRoute.RequiredParameters.moduleId).ValidInteger));
            }
        }
        
        /// <summary>
        /// sql-log/&lt;requestId:number&gt;
        /// </summary>
        public static SqlLogRoute SqlLog {
            get {
                return ((SqlLogRoute)(new SqlLogRoute().DefaultForArea().Is("").DefaultForController().Is<OpenUni.Web.UI.Controllers.SqlLogController>().DefaultForAction().Is("View")));
            }
        }
        
        /// <summary>
        /// people/&lt;username&gt;/&lt;personId:guid&gt;
        /// </summary>
        public static ProfileByPersonDetailsRoute ProfileByPersonDetails {
            get {
                return ((ProfileByPersonDetailsRoute)(new ProfileByPersonDetailsRoute().DefaultForArea().Is("People").DefaultForController().Is<OpenUni.Web.UI.Controllers.People.ProfilesController>().DefaultForAction().Is("Show").Restrict(ProfileByPersonDetailsRoute.RequiredParameters.personId).ValidGuid));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class DepartmentsRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public DepartmentsRoute() : 
                    base("Departments", "departments") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class DepartmentByNameRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public DepartmentByNameRoute() : 
                    base("DepartmentByName", "departments/<departmentName>") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
                
                public const string departmentName = "departmentName";
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class HomepageRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public HomepageRoute() : 
                    base("Homepage", "/[controller]") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
                
                public const string controller = "controller";
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class aboutRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public aboutRoute() : 
                    base("about", "/about") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class LoginRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public LoginRoute() : 
                    base("Login", "login") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class LogoutRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public LogoutRoute() : 
                    base("Logout", "login/logout") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class Login_ChooseRoleRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public Login_ChooseRoleRoute() : 
                    base("Login_ChooseRole", "login/chooserole") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class ModulesRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public ModulesRoute() : 
                    base("Modules", "modules") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class ModuleByIdRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public ModuleByIdRoute() : 
                    base("ModuleById", "modules/<moduleId>/[moduleName]") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
                
                public const string moduleId = "moduleId";
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
                
                public const string moduleName = "moduleName";
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class SqlLogRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public SqlLogRoute() : 
                    base("SqlLog", "sql-log/<requestId>") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
        public partial class ProfileByPersonDetailsRoute : Castle.MonoRail.Framework.Routing.PatternRoute {
            
            public ProfileByPersonDetailsRoute() : 
                    base("ProfileByPersonDetails", "people/<username>/<personId>") {
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class RequiredParameters {
                
                public const string username = "username";
                
                public const string personId = "personId";
            }
            
            [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
            public partial class OptionalParameters {
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class Routes {
        
        protected Castle.MonoRail.Framework.IEngineContext engineContext;
        
        public Routes(Castle.MonoRail.Framework.IEngineContext engineContext) {
            this.engineContext = engineContext;
        }
        
        /// <summary>
        /// departments
        /// </summary>
        public virtual string Departments() {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            return RouteDefinitions.Departments.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// departments/&lt;departmentName&gt;
        /// </summary>
        public virtual string DepartmentByName(string departmentName) {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            routeParameters.Add("departmentName", departmentName);
            return RouteDefinitions.DepartmentByName.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// /[controller]
        /// </summary>
        public virtual string Homepage(string controller) {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            routeParameters.Add("controller", controller);
            return RouteDefinitions.Homepage.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// /about
        /// </summary>
        public virtual string about() {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            return RouteDefinitions.about.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// login
        /// </summary>
        public virtual string Login() {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            return RouteDefinitions.Login.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// login/logout
        /// </summary>
        public virtual string Logout() {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            return RouteDefinitions.Logout.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// login/chooserole
        /// </summary>
        public virtual string Login_ChooseRole() {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            return RouteDefinitions.Login_ChooseRole.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// modules
        /// </summary>
        public virtual string Modules() {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            return RouteDefinitions.Modules.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// modules/&lt;moduleId:int&gt;/[moduleName]
        /// </summary>
        public virtual string ModuleById(int moduleId, string moduleName) {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            routeParameters.Add("moduleId", moduleId);
            routeParameters.Add("moduleName", moduleName);
            return RouteDefinitions.ModuleById.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// sql-log/&lt;requestId:number&gt;
        /// </summary>
        public virtual string SqlLog() {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            return RouteDefinitions.SqlLog.CreateUrl(routeParameters);
        }
        
        /// <summary>
        /// people/&lt;username&gt;/&lt;personId:guid&gt;
        /// </summary>
        public virtual string ProfileByPersonDetails(string username, System.Guid personId) {
            System.Collections.IDictionary routeParameters = Castle.MonoRail.Framework.Helpers.DictHelper.Create();
            routeParameters.Add("username", username);
            routeParameters.Add("personId", personId);
            return RouteDefinitions.ProfileByPersonDetails.CreateUrl(routeParameters);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHomeControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootHomeControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLoginControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootLoginControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootModulesControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootModulesControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootSqlLogControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootSqlLogControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalHomeControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPortalHomeControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalModulesControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPortalModulesControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPeopleProfilesControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPeopleProfilesControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootDepartmentsControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootDepartmentsControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Index {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "", "Departments", "Index");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Show {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.DepartmentsController), "", "Departments", "Show");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHomeControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootHomeControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference About {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.HomeController), "", "Home", "About");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Index {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.HomeController), "", "Home", "Index");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLoginControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootLoginControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference ChooseRole {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.LoginController), "", "Login", "ChooseRole");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Login {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.LoginController), "", "Login", "Login");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootModulesControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootModulesControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Index {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.ModulesController), "", "Modules", "Index");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Show {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.ModulesController), "", "Modules", "Show");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Students {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.ModulesController), "", "Modules", "Students");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootSqlLogControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootSqlLogControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference View {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.SqlLogController), "", "SqlLog", "View");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalHomeControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPortalHomeControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Index {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.HomeController), "Portal", "Home", "Index");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalModulesControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPortalModulesControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference MyModules {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Portal", "Modules", "MyModules");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Register {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Portal", "Modules", "Register");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Registered {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.Portal.ModulesController), "Portal", "Modules", "Registered");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPeopleProfilesControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPeopleProfilesControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Person {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.People.ProfilesController), "People", "Profiles", "Person");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Professor {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.People.ProfilesController), "People", "Profiles", "Professor");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference StaffMember {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(OpenUni.Web.UI.Controllers.People.ProfilesController), "People", "Profiles", "StaffMember");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootAreaNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        private RootDepartmentsControllerNode _departments;
        
        private RootHomeControllerNode _home;
        
        private RootLoginControllerNode _login;
        
        private RootModulesControllerNode _modules;
        
        private RootSqlLogControllerNode _sqlLog;
        
        private RootPortalAreaNode _portal;
        
        private RootPeopleAreaNode _people;
        
        public RootAreaNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
            this._departments = new RootDepartmentsControllerNode(this._services);
            this._home = new RootHomeControllerNode(this._services);
            this._login = new RootLoginControllerNode(this._services);
            this._modules = new RootModulesControllerNode(this._services);
            this._sqlLog = new RootSqlLogControllerNode(this._services);
            this._portal = new RootPortalAreaNode(this._services);
            this._people = new RootPeopleAreaNode(this._services);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootDepartmentsControllerNode Departments {
            get {
                return this._departments;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHomeControllerNode Home {
            get {
                return this._home;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLoginControllerNode Login {
            get {
                return this._login;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootModulesControllerNode Modules {
            get {
                return this._modules;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootSqlLogControllerNode SqlLog {
            get {
                return this._sqlLog;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPortalAreaNode Portal {
            get {
                return this._portal;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPeopleAreaNode People {
            get {
                return this._people;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootDepartmentsControllerNode : RootDepartmentsControllerActionNode {
        
        public RootDepartmentsControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootDepartmentsControllerViewNode Views {
            get {
                return new RootDepartmentsControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootDepartmentsControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHomeControllerNode : RootHomeControllerActionNode {
        
        public RootHomeControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHomeControllerViewNode Views {
            get {
                return new RootHomeControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHomeControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLoginControllerNode : RootLoginControllerActionNode {
        
        public RootLoginControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLoginControllerViewNode Views {
            get {
                return new RootLoginControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLoginControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootModulesControllerNode : RootModulesControllerActionNode {
        
        public RootModulesControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootModulesControllerViewNode Views {
            get {
                return new RootModulesControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootModulesControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootSqlLogControllerNode : RootSqlLogControllerActionNode {
        
        public RootSqlLogControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootSqlLogControllerViewNode Views {
            get {
                return new RootSqlLogControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootSqlLogControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalAreaNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        private RootPortalHomeControllerNode _home;
        
        private RootPortalModulesControllerNode _modules;
        
        public RootPortalAreaNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
            this._home = new RootPortalHomeControllerNode(this._services);
            this._modules = new RootPortalModulesControllerNode(this._services);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPortalHomeControllerNode Home {
            get {
                return this._home;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPortalModulesControllerNode Modules {
            get {
                return this._modules;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalHomeControllerNode : RootPortalHomeControllerActionNode {
        
        public RootPortalHomeControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPortalHomeControllerViewNode Views {
            get {
                return new RootPortalHomeControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPortalHomeControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPortalModulesControllerNode : RootPortalModulesControllerActionNode {
        
        public RootPortalModulesControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPortalModulesControllerViewNode Views {
            get {
                return new RootPortalModulesControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPortalModulesControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPeopleAreaNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        private RootPeopleProfilesControllerNode _profiles;
        
        public RootPeopleAreaNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
            this._profiles = new RootPeopleProfilesControllerNode(this._services);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPeopleProfilesControllerNode Profiles {
            get {
                return this._profiles;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPeopleProfilesControllerNode : RootPeopleProfilesControllerActionNode {
        
        public RootPeopleProfilesControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPeopleProfilesControllerViewNode Views {
            get {
                return new RootPeopleProfilesControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPeopleProfilesControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
}
namespace OpenUni.Web.UI.Controllers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class DepartmentsController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootDepartmentsControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootDepartmentsControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootDepartmentsControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootDepartmentsControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootDepartmentsControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootDepartmentsControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class HomeController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootHomeControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootHomeControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootHomeControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootHomeControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootHomeControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootHomeControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class LoginController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootLoginControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootLoginControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootLoginControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootLoginControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootLoginControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootLoginControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class ModulesController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootModulesControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootModulesControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootModulesControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootModulesControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootModulesControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootModulesControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class SqlLogController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootSqlLogControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootSqlLogControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootSqlLogControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootSqlLogControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootSqlLogControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootSqlLogControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
}
namespace OpenUni.Web.UI.Controllers.Portal {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class HomeController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPortalHomeControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPortalHomeControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPortalHomeControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPortalHomeControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPortalHomeControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPortalHomeControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class ModulesController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPortalModulesControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPortalModulesControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPortalModulesControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPortalModulesControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPortalModulesControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPortalModulesControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
}
namespace OpenUni.Web.UI.Controllers.People {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class ProfilesController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPeopleProfilesControllerNode MyActions {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPeopleProfilesControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPeopleProfilesControllerViewNode MyViews {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPeopleProfilesControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual OpenUni.Web.UI.SiteMap.RootPeopleProfilesControllerRouteNode MyRoutes {
            get {
                return new OpenUni.Web.UI.SiteMap.RootPeopleProfilesControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
}
